--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/cano/Wallpapers/sunset.png"

-- Special
background="#282828"
foreground="#D4BE98"
cursor="#c5c5c5"

-- Colors
color0="#282828"
color1="#D95222"
color2="#E05D24"
color3="#DD6325"
color4="#E37226"
color5="#C3912C"
color6="#D5952C"
color7="#c5c5c5"
color8="#725d5d"
color9="#D95222"
color10="#E05D24"
color11="#DD6325"
color12="#E37226"
color13="#C3912C"
color14="#D5952C"
color15="#D4BE98"
