[colors]
background = '#2828288e'
black = '#282828'
blue = '#D95222'
cursor = '#c5c5c5'
cyan = '#E05D24'
foreground = '#D4BE98'
green = '#DD6325'
magenta = '#E37226'
red = '#C3912C'
tabs = '#D4BE98'
tabs-active = '#D5952C'
white = '#D4BE98'
yellow = '#c5c5c5'
dim-black = '#2828288e'
dim-blue = '#D952228e'
dim-cyan = '#E05D248e'
dim-foreground = '#D4BE988e'
dim-green = '#DD63258e'
dim-magenta = '#E372268e'
dim-red = '#C3912C8e'
dim-white = '#D5952C8e'
dim-yellow = '#c5c5c58e'
light-black = '#D95222'
light-blue = '#E05D24'
light-cyan = '#DD6325'
light-foreground = '#E37226'
light-green = '#C3912C'
light-magenta = '#D5952C'
light-red = '#D4BE98'
light-white = '#D95222'
light-yellow = '#E05D24'
