# Shell variables
# Generated by 'wal'
wallpaper="/home/cano/Wallpapers/sunset.png"

# Special
background='#282828'
foreground='#D4BE98'
cursor='#c5c5c5'

# Colors
color0='#282828'
color1='#D95222'
color2='#E05D24'
color3='#DD6325'
color4='#E37226'
color5='#C3912C'
color6='#D5952C'
color7='#c5c5c5'
color8='#725d5d'
color9='#D95222'
color10='#E05D24'
color11='#DD6325'
color12='#E37226'
color13='#C3912C'
color14='#D5952C'
color15='#D4BE98'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
