[colors.primary]
background = "#282828"
foreground = "#D4BE98"

[colors.cursor]
text = "#282828"
cursor = "#D4BE98"

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#D4BE98"

[colors.search.matches]
foreground = "#282828"
background = "#D4BE98"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#725d5d"
background = "#c5c5c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#282828"
red = "#D95222"
green = "#E05D24"
yellow = "#DD6325"
blue = "#E37226"
magenta = "#C3912C"
cyan = "#D5952C"
white = "#c5c5c5"

[colors.bright]
black = "#725d5d"
red = "#D95222"
green = "#E05D24"
yellow = "#DD6325"
blue = "#E37226"
magenta = "#C3912C"
cyan = "#D5952C"
white = "#D4BE98"

[colors.dim]
black = "#D4BE98"
red = "#D95222"
green = "#C3912C"
yellow = "#DD6325"
blue = "#E37226"
magenta = "#E05D24"
cyan = "#D5952C"
white = "#725d5d"

